// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model7.Models;

#nullable disable

namespace Model7.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Model7.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = false,
                            Name = "Learn C#"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Name = "Learn EF Core"
                        },
                        new
                        {
                            Id = 3,
                            IsComplete = false,
                            Name = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            IsComplete = false,
                            Name = "Learn EF Core Power Tools"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
